### PR TITLE
Update `task_policy_tag` to `to_task_t` from HPX 1.8.1

### PR DESCRIPTION
**Pull request by msimberg**

### CODE REVIEW

**Review by hkaiser — APPROVED** [review]
LGTM, thanks!

**Comment by msimberg** [comment]
@hkaiser you probably noticed that I only changed the minimum necessary here to get `policy(task)` working again.

I'll happily separately add the other overloads as well, but I wasn't yet sure what the correct behaviour there is... And if you have thoughts on the correct behaviour please let me know. Basically what I'm thinking about is:
- Should `kokkos_policy<HPX>` with `to_seq` change the execution space type to `Serial` or just restrict the HPX execution space to use one thread? Probably the latter.
- Should `kokkos_policy<Serial>` with `to_par` be a compilation error or be simply ignored (serial is after all a valid implementation for `par`)? Probably the latter?
- Should any Kokkos policy with `to_unseq` do anything? Should it depend on if Kokkos has enabled compiler-assisted vectorization? Unsure.
- etc.

**Comment by msimberg** [comment]
HPX will need some fixes for the nvcc build (some `lock_guard`s will need their template parameters back, possibly some other stuff as well). I'll get back to this next week.

**Comment by hkaiser** [comment]
@msimberg I wouldn't overdo here. Let's go with the minimally necessary changes as you suggested (i.e. the 'latter' in both cases).

**Comment by msimberg** [comment]
That one test failure is a false positive (related to timing).

**Pull request merged**
